services:
  web-app:
    build: ./app
    command: python ./backend/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/src/app/
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env.dev

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev

volumes:
  postgres_data:
